<?php
    const ERROR_CONNECT_DATA = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No se pudo conectar a la base de datos.</p>";
    const ERROR_CONNECT_DATA_COMBOBOX = "<option>DATABASE NOT CONNECTED!!!</option>";
    const ERROR_UNKNOWN_EMPLOYEE = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No existe el puesto en la oficina.</p>";
    const ERROR_NOT_CREATE_USERNAME = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Por motivos de seguridad no se ha podido hacer el registro. Pruebe con otro nombre.</p>";
    const OK_CREATE_USERNAME = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Trabajador registrado correctamente.</p>";
    const ERROR_WORKER_NOT_FOUND = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No hay información disponible del trabajador asignado.</p>";
    const ERROR_WORKER_NAME_NOT_FOUND = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No existe ese trabajador.</p>";
    const ERROR_NOT_UPDATE_USERNAME = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Por motivos de seguridad no se ha podido modificar el registro.</p>";
    const OK_UPDATE_USERNAME = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Datos del trabajador asignado modificados correctamente.</p>";
    const ERROR_WORKER_NOT_EXISTS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No existe el trabajador asignado.</p>";
    const ERROR_NOT_WORKERS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No hay trabajadores disponibles.</p>";
    const ERROR_NOT_DELETE_USERNAME = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Por motivos de seguridad no se ha podido eliminar el registro.</p>";
    const OK_DELETE_USERNAME = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Datos del trabajador asignado eliminados correctamente.</p>";
    const ERROR_TASK_CONSULTING_NOT_EXISTS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No existe esa labor o tarea.</p>";
    const ERROR_POST_EMPLOYEE_NOT_FOUND = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No existe el puesto asignado.</p>";
    const ERROR_TASK_CONSULTING_NOT_UPLOADED = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Por motivos de seguridad no se ha podido publicar la consulta. Pruebe con otros parámetros.</p>";
    const OK_TASK_CONSULTING_UPLOADED = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Consulta publicada correctamente. Nuestros agentes de la empresa recibirán su petición en menos de 24 horas.</p>";
    const ERROR_ACCESS_LOGIN = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> El usuario o contraseña no son correctos.</p>";
    const ERROR_NO_DATA_COMBOBOX = "<option>(Sin resultados)</option>";
    const ERROR_NO_NEWS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Aún no se han publicado noticias.</p>";
    const OK_PROGRESS_UPDATED = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Progreso actualizado correctamente.</p>";
    const ERROR_PROGRESS_NOT_UPDATED = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No se ha podido actualizar el progreso.</p>";
    const ERROR_CLIENT_NOT_EXISTS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No se encontró al cliente.</p>";
    const ERROR_NOT_ORDERS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No se han realizado pedidos todavía.</p>";
    const ERROR_ORDER_NOT_EXISTS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No se encontró el pedido.</p>";
    const OK_NOTICE_POSTED = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Noticia publicada en el telediario correctamente.</p>";
    const ERROR_NOTICE_NOT_POSTED = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Por motivos de seguridad no se ha podido publicar la noticia en el telediario. Pruebe con otros parámetros.</p>";
    const OK_NOTICE_UPDATED = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Noticia actualizada correctamente.</p>";
    const ERROR_NOTICE_NOT_UPDATED = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Por motivos de seguridad no se ha podido actualizar la noticia en el telediario. Pruebe con otros parámetros.</p>";
    const OK_NOTICE_DELETED = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Noticia eliminada del telediario correctamente.</p>";
    const ERROR_NOTICE_NOT_EXISTS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No se encontró la noticia en el telediario.</p>";
    const ERROR_NOTICE_NOT_DELETED = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Por motivos de seguridad no se ha podido eliminar la noticia del telediario.";
    const ERROR_DIFFERENT_PASS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Las claves no coinciden.</p>";
    const OK_PASS_UPDATED = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> La clave fue actualizada correctamente. <a href='iniciarsesion.php'>Volver a iniciar sesión</a>.</p>";
    const ERROR_PASS_NOT_UPDATED = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> Por motivos de seguridad no se ha podido actualizar tu clave. Pruebe con otros parámetros.</p>";
    const ERROR_FILEXML_NOT_EXISTS = "<p><img src='Imágenes/Advice.png' width='15' alt='Advertencia'/> No se encontró el fichero ";
    const OK_IMPORT_WORKERS_FROM_XML = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Se han importado todos los trabajadores desde XML correctamente.</p>";
    const OK_IMPORT_TASKS_FROM_XML = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Se han importado todos las peticiones desde XML correctamente.</p>";
    const OK_IMPORT_NEWS_FROM_XML = "<p><img src='Imágenes/Verify.png' width='15' alt='Verificado'/> Se han importado todos las noticias del telediario desde XML correctamente.</p>";